version: "3"
services:
  console-rdb:
    image: mysql:8.0.33
    container_name: console-rdb
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "contact"
      TZ: "Asia/Seoul"
      LANG: "C.UTF_8"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - "./docker/console_rdb/mysql_data:/var/lib/mysql"
      - "./contact-file-interact/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

  console-gui:
    image: mysql:8.0.33
    container_name: console-gui
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "contact"
      TZ: "Asia/Seoul"
      LANG: "C.UTF_8"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - "./docker/console_gui/mysql_data:/var/lib/mysql"
      - "./contact-file-interact/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
